# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

sudo: required

os:
  - linux
#  - osx

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:
#    - LAZ_PKG=true   # Use the latest version from the default package manager
#    - LAZ_VER=1.0.14 # Use specific (binary) release
#    - LAZ_VER=1.2.6
#    - LAZ_VER=1.4.4
     - LAZ_VER=1.6

matrix:
  include:
#    - os: linux
#      env: LAZ_VER=1.2.6  LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
#    - os: linux
#      env: LAZ_VER=1.4.4  LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
#    - os: linux
#      env: LAZ_VER=1.6    LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
#    - os: linux
#      env: LAZ_VER=1.2.6  LAZ_ENV=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"
#    - os: linux
#      env: LAZ_VER=1.4.4  LAZ_ENV=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"
#    - os: linux
#      env: LAZ_VER=1.6    LAZ_ENV=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"
#    - os: linux
#      env: LAZ_VER=1.2.6  LAZ_ENV=qemu-arm LAZ_OPT="--os=linux --cpu=arm --widgetset=nogui"
#    - os: linux
#      env: LAZ_VER=1.4.4  LAZ_ENV=qemu-arm LAZ_OPT="--os=linux --cpu=arm --widgetset=nogui"
#    - os: linux
#      env: LAZ_VER=1.6    LAZ_ENV=qemu-arm LAZ_OPT="--os=linux --cpu=arm --widgetset=nogui"

before_install:
    # Start virtual display server
  - sh -e /etc/init.d/xvfb start || true

install:
    # Install prerequisites (fpc/lazarus/wine/qemu)
  - sudo python ./.travis.install.py
  - svn co https://svn.atozed.com:444/svn/Indy10/trunk/Lib ./indy/Lib --username Indy-Public-RO --non-interactive --trust-server-cert 

script:
  - lazbuild $LAZ_OPT ./test/unittests/Unittests.lpi               # Build test project
#  - $LAZ_ENV ./bin/my_lazarus_tests --all --format=plain # Run my_lazarus_test testsuite
